[WIP]Add api post nippo
nisshiee/nippo pull request #88
Opened 2016-09-22 07:36 UTC by iida-hayato

- [x] add new,show,create,update
- [x] rspec new,show,create,update
- [ ] test by ios sample application

2016-09-22 07:41 UTC, iida-hayato commented
josnにエラーメッセージをどう渡すのが良いのか・・

2016-10-12 11:35 UTC, iida-hayato commented
@nisshiee @pataiji レビューお願いします

2016-10-13 00:32 UTC, nisshiee commented
「下書き」や「プレビュー」まわりの機能がWeb側にはあって、中途半端にそれらのための機能が混じってる気がしますが、API側の仕様としてこのへんどうします？

2016-10-13 00:43 UTC, nisshiee requested changes

2016-10-13 00:43 UTC, nisshiee commented on app/controllers/api/nippos_controller.rb
> +      flash.now[:alert] = @nippo.errors.values.flatten
flashは画面用？

2016-10-13 00:43 UTC, nisshiee commented on app/controllers/api/nippos_controller.rb
> +  def update
Web側は、「下書き」や「プレビュー」状態の日報を「送信」するときに `update` が呼ばれるようになってます。
なので、もし下書きプレビューを無しにするなら、 `update` 自体が不要っすね

2016-10-17 17:17 UTC, pataiji commented on app/controllers/api/api_controller.rb
> +  protect_from_forgery with: :null_session
自分は`skip_before_action :verify_authenticity_token`しか使ったことなかったんですが、`with: :null_session`なんてあったんですね。
sessionをリセットするみたいですがsession_idが変わるわけではないんでしょうか？
ログイン状態とかどうなるんだろう？

http://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection/ClassMethods.html#method-i-protect_from_forgery

> You can disable forgery protection on controller by skipping the verification before_action:
`skip_before_action :verify_authenticity_token`

2016-10-26 09:42 UTC, iida-hayato commented
> 「下書き」や「プレビュー」まわりの機能がWeb側にはあって、中途半端にそれらのための機能が混じってる気がしますが、API側の仕様としてこのへんどうします？

これは要らなそうなんで消します

2016-10-26 09:43 UTC, iida-hayato commented on app/controllers/api/nippos_controller.rb
> +      flash.now[:alert] = @nippo.errors.values.flatten
jsonでエラー情報を渡す設計ができてないんですよねー

いったん消しときます

2016-10-26 09:43 UTC, iida-hayato commented on app/controllers/api/nippos_controller.rb
> +  def update
こちらも不要っぽいので削除

2016-10-26 10:33 UTC, iida-hayato commented on app/controllers/api/api_controller.rb
> +  protect_from_forgery with: :null_session
一応上の形でも動いてたんでセッションまわりはdoorkeeperがやってくれてるっぽいです

またこちらも試した所問題なく動いたんでこっちにしておきます
`skip_before_action :verify_authenticity_token`

2016-10-26 10:53 UTC, iida-hayato commented
@nisshiee @pataiji 
もろもろ対応しました。

2016-11-02 10:18 UTC, iida-hayato commented
@pataiji null_sessionに戻しましたー

2016-11-02 10:50 UTC, pataiji commented
`skip_before_action :verify_authenticity_token`と`protect_from_forgery with: :null_session`なんですが、結果どちらでも大丈夫そうでした:pray: :pray:

CSRF protectionに通らなかった時の挙動
- `skip_before_action :verify_authenticity_token` -> 何もしない(そもそもprotectionしてない)
- `protect_from_forgery with: :null_session` -> sessionを空にする

APIなのでsessionにデータ入れてゴニョゴニョみたいなことはしないと思うので、結論どちらでも問題ないということになるのかなと。

※ RailsのドキュメントでもAPIアクセス(`format: :json`)の時は`protect_from_forgery`自体を有効にしていないので、`skip_before_action :verify_authenticity_token`と同じ状態です。

http://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection.html
> It's important to remember that XML or JSON requests are also affected and if you're building an API you should change forgery protection method in ApplicationController (by default: :exception):

> ```ruby
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }
end
```

2016-11-02 10:51 UTC, pataiji commented
LGTM :+1:

2016-11-12 01:41 UTC, nisshiee commented on app/controllers/api/nippos_controller.rb
> +  def new
【相談したい】
これ、テンプレートを取得するんだったらTemplateをGETするAPI設計にした方が素直な気もしますがいかがでしょ？

2016-11-12 01:42 UTC, nisshiee requested changes

2016-11-12 01:42 UTC, nisshiee commented on config/routes.rb
> +    resources :nippos, only: %i(new create index show update)
`update`が消えたはずー

2016-11-14 13:14 UTC, pataiji commented on app/controllers/api/nippos_controller.rb
> +  def new
確かに、言われてみてそんな気がしました。
ただ`reported_for`を扱うことを考えると
nippoリソースを返すこの実装でもいいような。

2016-11-14 13:21 UTC, nisshiee commented on app/controllers/api/nippos_controller.rb
> +  def new
うーむ、これちょっと落ち着いて考えてみても良いかも

REST API設計に`GET new`は無いよね
っつーことは何かしらのやりようがある気がする

2016-11-14 14:27 UTC, iida-hayato commented on config/routes.rb
> +    resources :nippos, only: %i(new create index show update)
なるほどこれ見逃しやすそうなポイントですね

2016-11-14 14:32 UTC, iida-hayato commented on app/controllers/api/nippos_controller.rb
> +  def new
テンプレートと日付を組み合わせて当日の日報の雛形的な何かをgetするということで
その何かが日報なのかまだ日報ではないのか問題。

でも最早テンプレートでは無いんですよねー
nippo/何か GET
みたい感じかなと

2016-11-18 12:40 UTC, iida-hayato commented on app/controllers/api/nippos_controller.rb
> +  def new
一般論として日付ってビジネスロジックに近しいところにあるからサーバから貰ったほうが良い気がするんですよねー


例えば休日祝日とか欲しくなったらサーバでやりたいよねーみたいな

今回はどうだろう?

2016-11-21 12:45 UTC, iida-hayato commented on app/controllers/api/nippos_controller.rb
> +  def new
なんなら機能絞りまくって
雑感だけpostする口があれば十分な気もするw

2016-11-21 13:48 UTC, nisshiee commented on app/controllers/api/nippos_controller.rb
> +  def new
絶対サーバサイドのテンプレ大改造構想を先にやったほうがいろいろ嬉しいよなぁ・・・・

2018-12-10 03:50 UTC, closed without merging